[package]
name = "pdf-lens"
version = "0.1.0"
edition = "2024"
authors = ["Kaede Fujisaki"]
readme = "README.md"
license = "AGPL-3.0-or-later"
repository = "https://github.com/ledyba/pdf-lens.rs"
keywords = ["pdf"]

[dependencies]
anyhow = "1.0.98"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [ "std", "env-filter", "chrono" ] }
clap = "4.5.23"
lopdf = "0.36.0"
